### ISSUE TITLE
[git] Error when trying to fetch an empty repository

### ISSUE THREAD

**Issue by albertinisg** [grimoirelab/perceval#102]
I've found that in `git` backend, when trying to fetch an empty repository, it returns the following error:
```bash
$ perceval git https://github.com/ethereum/branding.git
[2016-12-23 11:49:31,513] - Sir Perceval is on his quest.
[2016-12-23 11:49:31,517] - Fetching commits: 'https://github.com/ethereum/branding.git' git repository from 1970-01-01 00:00:00+00:00; all branches
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev2-py3.5.egg/perceval/backends/core/git.py", line 261, in run
    for commit in commits:
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev2-py3.5.egg/perceval/backend.py", line 192, in decorator
    for data in func(self, *args, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev2-py3.5.egg/perceval/backends/core/git.py", line 109, in fetch
    commits = self.__fetch_and_parse_log(from_date, branches)
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev2-py3.5.egg/perceval/backends/core/git.py", line 122, in __fetch_and_parse_log
    repo = self.__create_and_update_git_repository()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev2-py3.5.egg/perceval/backends/core/git.py", line 131, in __create_and_update_git_repository
    repo.pull()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev2-py3.5.egg/perceval/backends/core/git.py", line 660, in pull
    self._exec(cmd_reset, cwd=self.dirpath, env={'LANG' : 'C'})
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev2-py3.5.egg/perceval/backends/core/git.py", line 790, in _exec
    raise RepositoryError(cause=cause)
perceval.errors.RepositoryError: git command - fatal: ambiguous argument 'origin': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/perceval", line 4, in <module>
    __import__('pkg_resources').run_script('perceval==0.5.0.dev2', 'perceval')
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 746, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev2-py3.5.egg/EGG-INFO/scripts/perceval", line 179, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev2-py3.5.egg/EGG-INFO/scripts/perceval", line 100, in main
    cmd.run()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev2-py3.5.egg/perceval/backends/core/git.py", line 268, in run
    raise RuntimeError(str(e))
RuntimeError: git command - fatal: ambiguous argument 'origin': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
I know that it doesn't makes sense to fetch an empty repository, but we don't know when it's going to have information so in my opinion we still need to track it. Maybe a warning instead of error?

**Comment by sduenas** [comment]
Fixed!
