### ISSUE TITLE
[git] Error when trying to fetch a repo in 'detached HEAD' state

### ISSUE THREAD

**Issue by albertinisg** [grimoirelab/perceval#105]
When trying to fetch a `git` repo in 'detached HEAD' state, it returns the following error:
```bash
perceval git https://gerrit.automotivelinux.org/gerrit/zzz_acl/staging_acl
[2017-01-04 12:04:28,989] - Sir Perceval is on his quest.
[2017-01-04 12:04:28,990] - Fetching commits: 'https://gerrit.automotivelinux.org/gerrit/zzz_acl/staging_acl' git repository from 1970-01-01 00:00:00+00:00; all branches
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev2-py3.5.egg/perceval/backends/core/git.py", line 261, in run
    for commit in commits:
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev2-py3.5.egg/perceval/backend.py", line 192, in decorator
    for data in func(self, *args, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev2-py3.5.egg/perceval/backends/core/git.py", line 109, in fetch
    commits = self.__fetch_and_parse_log(from_date, branches)
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev2-py3.5.egg/perceval/backends/core/git.py", line 122, in __fetch_and_parse_log
    repo = self.__create_and_update_git_repository()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev2-py3.5.egg/perceval/backends/core/git.py", line 131, in __create_and_update_git_repository
    repo.pull()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev2-py3.5.egg/perceval/backends/core/git.py", line 660, in pull
    self._exec(cmd_reset, cwd=self.dirpath, env={'LANG' : 'C'})
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev2-py3.5.egg/perceval/backends/core/git.py", line 790, in _exec
    raise RepositoryError(cause=cause)
perceval.errors.RepositoryError: git command - fatal: ambiguous argument 'origin': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/perceval", line 4, in <module>
    __import__('pkg_resources').run_script('perceval==0.5.0.dev2', 'perceval')
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 746, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev2-py3.5.egg/EGG-INFO/scripts/perceval", line 179, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev2-py3.5.egg/EGG-INFO/scripts/perceval", line 100, in main
    cmd.run()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev2-py3.5.egg/perceval/backends/core/git.py", line 268, in run
    raise RuntimeError(str(e))
RuntimeError: git command - fatal: ambiguous argument 'origin': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by albertinisg** [comment]
Not sure if it's the same issue but, among the huge list of CodeAurora repositories, I've found many of them with a similar behavior:
```bash
perceval -g git https://source.codeaurora.org/external/criu/criu
[2017-01-31 12:25:11,940 - root - INFO] - Sir Perceval is on his quest.
[2017-01-31 12:25:11,942 - perceval.backends.core.git - INFO] - Fetching commits: 'https://source.codeaurora.org/external/criu/criu' git repository from 1970-01-01 00:00:00+00:00; all branches
[2017-01-31 12:25:11,943 - perceval.backends.core.git - DEBUG] - Running command git clone https://source.codeaurora.org/external/criu/criu /home/amartin/.perceval/repositories/https://source.codeaurora.org/external/criu/criu (cwd: None, env: {'LANG': 'C'})
[2017-01-31 12:25:16,077 - perceval.backends.core.git - DEBUG] - Cloning into '/home/amartin/.perceval/repositories/https://source.codeaurora.org/external/criu/criu'...
warning: remote HEAD refers to nonexistent ref, unable to checkout.


[2017-01-31 12:25:16,078 - perceval.backends.core.git - DEBUG] - Git https://source.codeaurora.org/external/criu/criu repository cloned into /home/amartin/.perceval/repositories/https://source.codeaurora.org/external/criu/criu
[2017-01-31 12:25:16,078 - perceval.backends.core.git - DEBUG] - Running command git count-objects -v (cwd: /home/amartin/.perceval/repositories/https://source.codeaurora.org/external/criu/criu, env: {'LANG': 'C'})
[2017-01-31 12:25:16,080 - perceval.backends.core.git - DEBUG] - 
[2017-01-31 12:25:16,080 - perceval.backends.core.git - DEBUG] - Git https://source.codeaurora.org/external/criu/criu repository has 27495 objects
[2017-01-31 12:25:16,080 - perceval.backends.core.git - DEBUG] - Running command git fetch origin (cwd: /home/amartin/.perceval/repositories/https://source.codeaurora.org/external/criu/criu, env: {'LANG': 'C'})
[2017-01-31 12:25:17,103 - perceval.backends.core.git - DEBUG] - 
[2017-01-31 12:25:17,103 - perceval.backends.core.git - DEBUG] - Running command git reset --hard origin (cwd: /home/amartin/.perceval/repositories/https://source.codeaurora.org/external/criu/criu, env: {'LANG': 'C'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.6.0.dev1-py3.5.egg/perceval/backend.py", line 309, in run
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.6.0.dev1-py3.5.egg/perceval/backend.py", line 359, in decorator
    for data in func(self, *args, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.6.0.dev1-py3.5.egg/perceval/backends/core/git.py", line 114, in fetch
    commits = self.__fetch_and_parse_log(from_date, branches)
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.6.0.dev1-py3.5.egg/perceval/backends/core/git.py", line 130, in __fetch_and_parse_log
    repo = self.__create_and_update_git_repository()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.6.0.dev1-py3.5.egg/perceval/backends/core/git.py", line 141, in __create_and_update_git_repository
    repo.pull()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.6.0.dev1-py3.5.egg/perceval/backends/core/git.py", line 738, in pull
    self._exec(cmd_reset, cwd=self.dirpath, env={'LANG' : 'C'})
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.6.0.dev1-py3.5.egg/perceval/backends/core/git.py", line 881, in _exec
    raise RepositoryError(cause=cause)
perceval.errors.RepositoryError: git command - fatal: ambiguous argument 'origin': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/perceval", line 4, in <module>
    __import__('pkg_resources').run_script('perceval==0.6.0.dev1', 'perceval')
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 746, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.6.0.dev1-py3.5.egg/EGG-INFO/scripts/perceval", line 188, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.6.0.dev1-py3.5.egg/EGG-INFO/scripts/perceval", line 106, in main
    cmd.run()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.6.0.dev1-py3.5.egg/perceval/backend.py", line 318, in run
    raise RuntimeError(str(e))
RuntimeError: git command - fatal: ambiguous argument 'origin': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

```
See the list here: https://github.com/Bitergia/projects-linuxfoundation/blob/master/projects.json#L4478

**Comment by jgbarah** [comment]
Just to clarify, why is the git repo in detached state? 

Besides, this is when running Perceval on a fresh repo (fresh after cloning the repo), or after the repo has been updated (after git fetch; git merge (or git rebase)).

Another one: this is running Perceval for the first time in the repo, or running it for a subsequent run, when Perceval itself tries to sync the repo?

**Comment by albertinisg** [comment]
There are several use cases. The first example, shows a repository in detached state because there are lo branches:
```bash
$ git clone https://gerrit.automotivelinux.org/gerrit/zzz_acl/staging_acl
Cloning into 'staging_acl'...
remote: Total 6 (delta 0), reused 6 (delta 0)
Unpacking objects: 100% (6/6), done.
Checking connectivity... done.
Note: checking out '015118e7a1ab409f7e75888cfc2406388cc11a9f'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

$ git branch --list
* (no branch)
```
Another example is this other repo. When we clone it, it seems to be empty:
```bash
$ git clone https://source.codeaurora.org/external/criu/criu
Cloning into 'criu'...
remote: Counting objects: 27495, done.
remote: Total 27495 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (27495/27495), 5.09 MiB | 264.00 KiB/s, done.
Resolving deltas: 100% (19987/19987), done.
Checking connectivity... done.
warning: remote HEAD refers to nonexistent ref, unable to checkout.
$ git status
On branch master

Initial commit

nothing to commit (create/copy files and use "git add" to track)
```
But the information is inside the remotes:
```bash
$ git branch -r
  origin/criu-org/br-1.3-stable
  origin/criu-org/br-1.5-stable
  origin/criu-org/master
  origin/criu-org/p.haul
$ git checkout origin/criu-org/master
Note: checking out 'origin/criu-org/master'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at a2a0e2f... test/rpc: dont use shell-job

$ git log --pretty=format:"%h - %an, %ar : %s"
a2a0e2f - Andrew Vagin, 1 year, 9 months ago : test/rpc: dont use shell-job
fe0afaa - Andrew Vagin, 1 year, 9 months ago : test/rpc: unlink pidfile at the end
bc3ee6c - Andrew Vagin, 1 year, 9 months ago : jenkins: use tmpfs for images in criu-iter
4834c39 - Andrey Vagin, 1 year, 9 months ago : jenkins/criu-iter: reduce a number of jobs
...
```
This happens on fresh repositories, and also running Perceval for the first time in the repo.

**Comment by sduenas** [comment]
The tool crashes when tries to make a `git rest` to `origin`. This command is called after a `fetch` and it is needed to keep up to date the repository. For any reason, `origin` reference is ambiguous, so it fails.
On detached states, it is not needed to reset the repo.

**Comment by sduenas** [comment]
@jgbarah after reading some posts about git and how cloning works, what leads to a detached state is the `checkout` that `git clone` does once it has fetched data from the remote repository. The last step in a `clone` is a checkout to stablish a local branch.

This local branch is set to anything `HEAD` refers on the origin repository. It can refer to a branch or a commit. When it points to a commit the local branch will be set as detached.

[Detached HEAD](http://stackoverflow.com/a/3965714)
