### ISSUE TITLE
[meetup] Handle Rate Limit doing retrieving Meetup groups

### ISSUE THREAD

**Issue by albertinisg** [grimoirelab/perceval#126]
Seems requests go way too fast retrieving items, and the retrieval leads into a `429` error sometimes.

An approach could be handling the `X-RateLimit-Remaining` and as soon as it gets over, sleep the process for the amount of seconds in `X-RateLimit-Reset`.

Traceback error:

```python
[2017-03-13 12:12:34,767 - requests.packages.urllib3.connectionpool - DEBUG] - "GET /Austin-Puppet-User-Group/events/qdncjlytqblb/comments?page=200&key=xxxx&sign=true HTTP/1.1" 429 87
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.7.0.dev3-py3.5.egg/perceval/backend.py", line 309, in run
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.7.0.dev3-py3.5.egg/perceval/backend.py", line 359, in decorator
    for data in func(self, *args, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.7.0.dev3-py3.5.egg/perceval/backends/core/meetup.py", line 105, in fetch
    event['comments'] = self.__fetch_and_parse_comments(event_id)
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.7.0.dev3-py3.5.egg/perceval/backends/core/meetup.py", line 193, in __fetch_and_parse_comments
    for raw_page in raw_pages:
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.7.0.dev3-py3.5.egg/perceval/backends/core/meetup.py", line 380, in comments
    for page in self._fetch(resource, params):
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.7.0.dev3-py3.5.egg/perceval/backends/core/meetup.py", line 424, in _fetch
    r.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/perceval", line 4, in <module>
    __import__('pkg_resources').run_script('perceval==0.7.0.dev3', 'perceval')
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 746, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.7.0.dev3-py3.5.egg/EGG-INFO/scripts/perceval", line 191, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.7.0.dev3-py3.5.egg/EGG-INFO/scripts/perceval", line 109, in main
    cmd.run()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.7.0.dev3-py3.5.egg/perceval/backend.py", line 314, in run
    raise RuntimeError(str(e))
RuntimeError: 429 Client Error: Too Many Requests
```

**Comment by sduenas** [comment]
This is fixed now but I would like to change the code that manages this part, making it more generic. I used the same code we have in GitHub backend. This code has some problems but it is enough for now to make it work.
