### ISSUE TITLE
[git] Backend fails fetching git repository without branches (but with tags)

### ISSUE THREAD

**Issue by albertinisg** [grimoirelab/perceval#131]
The repository doesn't have any branches or log, but contains information in tags:
```
  ~  git clone https://gerrit.wikimedia.org/r/openzim
Cloning into 'openzim'...
remote: Counting objects: 178, done
remote: Finding sources: 100% (4067/4067)
remote: Getting sizes: 100% (441/441)
remote: Total 4067 (delta 3150), reused 4067 (delta 3150)
Receiving objects: 100% (4067/4067), 1.60 MiB | 545.00 KiB/s, done.
Resolving deltas: 100% (3150/3150), done.
Checking connectivity... done.
warning: remote HEAD refers to nonexistent ref, unable to checkout.

  ~/openzim    master  git branch -a
  ~/openzim    master  git log
fatal: your current branch 'master' does not have any commits yet

 ~/openzim    master  git tag
1.0.0
1.0.2
r1.3
r1.4
zim4
zimwriterfs-1.0
```
Perceval traceback:
```python
$ perceval git 'https://gerrit.wikimedia.org/r/openzim'
[2017-03-24 13:57:07,670] - Sir Perceval is on his quest.
[2017-03-24 13:57:07,672] - Fetching commits: 'https://gerrit.wikimedia.org/r/openzim' git repository from 1970-01-01 00:00:00+00:00; all branches
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.7.0.dev4-py3.5.egg/perceval/backend.py", line 309, in run
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.7.0.dev4-py3.5.egg/perceval/backend.py", line 359, in decorator
    for data in func(self, *args, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.7.0.dev4-py3.5.egg/perceval/backends/core/git.py", line 114, in fetch
    commits = self.__fetch_and_parse_log(from_date, branches)
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.7.0.dev4-py3.5.egg/perceval/backends/core/git.py", line 130, in __fetch_and_parse_log
    repo = self.__create_and_update_git_repository()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.7.0.dev4-py3.5.egg/perceval/backends/core/git.py", line 141, in __create_and_update_git_repository
    repo.pull()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.7.0.dev4-py3.5.egg/perceval/backends/core/git.py", line 761, in pull
    self._exec(cmd_reset, cwd=self.dirpath, env={'LANG': 'C'})
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.7.0.dev4-py3.5.egg/perceval/backends/core/git.py", line 907, in _exec
    raise RepositoryError(cause=cause)
perceval.errors.RepositoryError: git command - fatal: ambiguous argument 'FETCH_HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/perceval", line 4, in <module>
    __import__('pkg_resources').run_script('perceval==0.7.0.dev4', 'perceval')
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 746, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.7.0.dev4-py3.5.egg/EGG-INFO/scripts/perceval", line 191, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.7.0.dev4-py3.5.egg/EGG-INFO/scripts/perceval", line 109, in main
    cmd.run()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.7.0.dev4-py3.5.egg/perceval/backend.py", line 318, in run
    raise RuntimeError(str(e))
RuntimeError: git command - fatal: ambiguous argument 'FETCH_HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by sduenas** [comment]
I can't reproduce the error with this repository. Looks like, the repo has changed somehow
```
openzim$ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master

openzim$ git log | wc
   3409   11230  102855

openzim$ perceval git 'https://gerrit.wikimedia.org/r/openzim' > /dev/null
[2017-04-06 11:11:11,691] - Sir Perceval is on his quest.
[2017-04-06 11:11:11,692] - Fetching commits: 'https://gerrit.wikimedia.org/r/openzim' git repository from 1970-01-01 00:00:00+00:00; all branches
[2017-04-06 11:11:12,776] - Fetch process completed: 505 commits fetched
[2017-04-06 11:11:12,776] - Sir Perceval completed his quest.
```

@albertinisg do you have any other repository like this?

**Comment by albertinisg** [comment]
I've been checking but couldn't find any... :cry: I will reopen it if I find another case.
