### ISSUE TITLE
[discourse] Error in __parse_topics_page because a None date

### ISSUE THREAD

**Issue by acs** [grimoirelab/perceval#150]
Trying to collect the discourse information from https://discourse.mozilla.org/ the next error appears:

```
2017-09-04 15:20:46,353 - grimoire_elk.arthur - ERROR - Error feeding ocean from discourse (https://discourse.mozilla.org/): None is not a valid date
Traceback (most recent call last):
  File "./grimoire_elk/arthur.py", line 117, in feed_backend
    ocean_backend.feed()
  File "./grimoire_elk/ocean/elastic.py", line 194, in feed
    for item in items:
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.0-py3.4.egg/perceval/backend.py", line 360, in decorator
    for data in func(self, *args, **kwargs):
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.0-py3.4.egg/perceval/backends/core/discourse.py", line 89, in fetch
    topics_ids = self.__fetch_and_parse_topics_ids(from_date)
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.0-py3.4.egg/perceval/backends/core/discourse.py", line 160, in __fetch_and_parse_topics_ids
    topics = self.__parse_topics_page(response)
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.0-py3.4.egg/perceval/backends/core/discourse.py", line 237, in __parse_topics_page
    updated_at = str_to_datetime(topic['last_posted_at'])
  File "/usr/local/lib/python3.4/dist-packages/grimoirelab_toolkit-0.1.0-py3.4.egg/grimoirelab/toolkit/datetime.py", line 111, in str_to_datetime
    raise InvalidDateError(date=str(ts))
grimoirelab.toolkit.datetime.InvalidDateError: None is not a valid date
```

**Comment by acs** [comment]
This issue is fixed with:

https://github.com/acs/perceval/commit/2c86d7efd6a33d45790256a01ab7ea3ee110826e
