### ISSUE TITLE
[git ]--latest-items fails in the second retrieval for a repository

### ISSUE THREAD

**Issue by acs** [grimoirelab/perceval#165]
The first collection of a git repository using "--latest-items" flag works.

```
(acs@dellx) ~ $ rm -rf ~/.perceval/repositories/
(acs@dellx) ~ $ perceval -g git --latest-items http://gerrit.onap.org/r/vvp/postgresql
...
[2017-09-25 23:00:08,970 - perceval.backends.core.git - INFO] - Fetch process completed: 1 commits fetched

```
But the second time (and the next ones) it fails:

```
(acs@dellx) ~ $ perceval -g git --latest-items http://gerrit.onap.org/r/vvp/postgresql
[2017-09-25 23:00:24,018 - root - INFO] - Sir Perceval is on his quest.
[2017-09-25 23:00:24,020 - perceval.backends.core.git - INFO] - Fetching latest commits: 'http://gerrit.onap.org/r/vvp/postgresql' git repository
[2017-09-25 23:00:24,020 - perceval.backends.core.git - DEBUG] - Running command git ls-remote -h -t origin (cwd: /home/acs/.perceval/repositories/http://gerrit.onap.org/r/vvp/postgresql, env: {'HOME': '/home/acs', 'PAGER': '', 'LANG': 'C'})
[2017-09-25 23:00:25,616 - perceval.backends.core.git - DEBUG] - 
[2017-09-25 23:00:25,616 - perceval.backends.core.git - DEBUG] - Running command git fetch-pack --include-tag --keep git://gerrit.onap.org/r/vvp/postgresql refs/heads/master (cwd: /home/acs/.perceval/repositories/http://gerrit.onap.org/r/vvp/postgresql, env: {'HOME': '/home/acs', 'PAGER': '', 'LANG': 'C'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.0-py3.5.egg/perceval/backend.py", line 310, in run
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.0-py3.5.egg/perceval/backend.py", line 360, in decorator
    for data in func(self, *args, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.0-py3.5.egg/perceval/backends/core/git.py", line 111, in fetch
    latest_items)
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.0-py3.5.egg/perceval/backends/core/git.py", line 139, in __fetch_from_repo
    commits = self.__fetch_newest_commits_from_repo(repo)
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.0-py3.5.egg/perceval/backends/core/git.py", line 173, in __fetch_newest_commits_from_repo
    hashes = repo.sync()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.0-py3.5.egg/perceval/backends/core/git.py", line 852, in sync
    pack_name, refs = self._fetch_pack()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.0-py3.5.egg/perceval/backends/core/git.py", line 981, in _fetch_pack
    env=self.gitenv)
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.0-py3.5.egg/perceval/backends/core/git.py", line 1200, in _exec
    raise RepositoryError(cause=cause)
perceval.errors.RepositoryError: git command - fatal: remote error: access denied or repository not exported: /r/vvp/postgresql


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/perceval", line 4, in <module>
    __import__('pkg_resources').run_script('perceval==0.9.0', 'perceval')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.0-py3.5.egg/EGG-INFO/scripts/perceval", line 192, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.0-py3.5.egg/EGG-INFO/scripts/perceval", line 110, in main
    cmd.run()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.0-py3.5.egg/perceval/backend.py", line 319, in run
    raise RuntimeError(str(e))
RuntimeError: git command - fatal: remote error: access denied or repository not exported: /r/vvp/postgresql
```

**Comment by acs** [comment]
Great! Time to do a quick test:

(acs@dellx) ~ $ perceval -g git --latest-items http://gerrit.onap.org/r/vvp/postgresql
[2017-11-07 14:02:11,895 - root - INFO] - Sir Perceval is on his quest.
[2017-11-07 14:02:11,897 - perceval.backends.core.git - DEBUG] - Running command git clone --mirror http://gerrit.onap.org/r/vvp/postgresql /home/acs/.perceval/repositories/http://gerrit.onap.org/r/vvp/postgresql-git (cwd: None, env: {'HOME': '/home/acs', 'LANG': 'C'})
[2017-11-07 14:02:13,772 - perceval.backends.core.git - DEBUG] - Cloning into bare repository '/home/acs/.perceval/repositories/http://gerrit.onap.org/r/vvp/postgresql-git'...
...
[2017-11-07 14:02:15,734 - perceval.backends.core.git - INFO] - Fetch process completed: 9 commits fetched
[2017-11-07 14:02:15,734 - root - INFO] - Sir Perceval completed his quest.
(acs@dellx) ~ $
....

And the second time:

```
(acs@dellx) ~ $ perceval -g git --latest-items http://gerrit.onap.org/r/vvp/postgresql
(acs@dellx) ~ $ perceval -g git --latest-items http://gerrit.onap.org/r/vvp/postgresql
[2017-11-07 14:03:38,171 - root - INFO] - Sir Perceval is on his quest.
[2017-11-07 14:03:38,173 - perceval.backends.core.git - INFO] - Fetching latest commits: 'http://gerrit.onap.org/r/vvp/postgresql' git repository
...
[2017-11-07 14:03:43,513 - perceval.backends.core.git - INFO] - Fetch process completed: 0 commits fetched
```

So yes, it is working!
