### ISSUE TITLE
Git Backend: Error when no commits are found

### ISSUE THREAD

**Issue by acs** [grimoirelab/perceval#17]
perceval -g git git://gerrit.libreoffice.org/benchmark --from-date "2016-03-09" 

    ...
    File "/usr/local/lib/python3.4/dist-packages/perceval/backends/git.py", line 396, in _handle_commit
    raise ParseError(cause=msg)
    perceval.errors.ParseError: commit expected on line 1

**Comment by sduenas** [comment]
Confirmed.
```
$ perceval -g git git://gerrit.libreoffice.org/benchmark --from-date "2016-03-09"
[2016-03-10 18:19:04,436 - root - INFO] - Sir Perceval is on his quest.
[2016-03-10 18:19:04,438 - perceval.backends.git - INFO] - Fetching commits: 'git://gerrit.libreoffice.org/benchmark' git repository from 2016-03-09 00:00:00+00:00
[2016-03-10 18:19:04,438 - root - DEBUG] - Running command git fetch origin (cwd: /home/sduenas/.perceval/repositories/git://gerrit.libreoffice.org/benchmark, env: {'LANG': 'C'})
[2016-03-10 18:19:04,692 - root - DEBUG] - 
[2016-03-10 18:19:04,692 - root - DEBUG] - Running command git reset --hard origin (cwd: /home/sduenas/.perceval/repositories/git://gerrit.libreoffice.org/benchmark, env: {'LANG': 'C'})
[2016-03-10 18:19:04,696 - root - DEBUG] - 
[2016-03-10 18:19:04,697 - root - DEBUG] - Git git://gerrit.libreoffice.org/benchmark repository pulled into /home/sduenas/.perceval/repositories/git://gerrit.libreoffice.org/benchmark
[2016-03-10 18:19:04,697 - root - DEBUG] - Running command git log --raw --numstat --pretty=fuller --decorate=full --all --reverse --topo-order --parents -M -C -c --remotes=origin --since=2016-03-09 00:00:00 +0000 (cwd: /home/sduenas/.perceval/repositories/git://gerrit.libreoffice.org/benchmark, env: {'PAGER': '', 'LANG': 'C'})
[2016-03-10 18:19:04,701 - root - DEBUG] - 
[2016-03-10 18:19:04,701 - root - DEBUG] - Git log fetched from git://gerrit.libreoffice.org/benchmark repository (/home/sduenas/.perceval/repositories/git://gerrit.libreoffice.org/benchmark)
Traceback (most recent call last):
  File "/home/sduenas/.local/lib/python3.4/site-packages/perceval/backends/git.py", line 208, in run
    for commit in commits:
  File "/home/sduenas/.local/lib/python3.4/site-packages/perceval/backend.py", line 163, in decorator
    for item in func(self, *args, **kwargs):
  File "/home/sduenas/.local/lib/python3.4/site-packages/perceval/backends/git.py", line 94, in fetch
    for commit in commits:
  File "/home/sduenas/.local/lib/python3.4/site-packages/perceval/backends/git.py", line 172, in parse_git_log_from_iter
    for commit in parser.parse():
  File "/home/sduenas/.local/lib/python3.4/site-packages/perceval/backends/git.py", line 369, in parse
    parsed = self.handlers[self.state](line)
  File "/home/sduenas/.local/lib/python3.4/site-packages/perceval/backends/git.py", line 400, in _handle_commit
    raise ParseError(cause=msg)
perceval.errors.ParseError: commit expected on line 1
```

**Comment by sduenas** [comment]
This command generates an empty commit log.

```
$ git log --raw --numstat --pretty=fuller --decorate=full --all --reverse --topo-order --parents -M -C -c --remotes=origin --since="2016-03-09 00:00:00 +0000"
```

**Comment by sduenas** [comment]
Fixed. It runs smoothly!

```
$ perceval git git://gerrit.libreoffice.org/benchmark --from-date "2016-03-09"
[2016-03-10 19:38:37,748] - Sir Perceval is on his quest.
[2016-03-10 19:38:37,749] - Fetching commits: 'git://gerrit.libreoffice.org/benchmark' git repository from 2016-03-09 00:00:00+00:00
[2016-03-10 19:38:38,603] - Fetch process completed: 0 commits fetched
[2016-03-10 19:38:38,603] - Sir Perceval completed his quest.
```

**Comment by acs** [comment]
Cool! Thanks @sduenas
