### ISSUE TITLE
[phabricator] Error retrieving Phabricator issues

### ISSUE THREAD

**Issue by albertinisg** [grimoirelab/perceval#178]
I did launch perceval (latest version) against our phab instance and got the following error:
```bash
$ perceval phabricator https://phabricator.bitergia.net -t XXXX > /dev/null
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 310, in run
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 360, in decorator
    for data in func(self, *args, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/phabricator.py", line 85, in fetch
    for task in self.__fetch_tasks(from_date):
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/phabricator.py", line 155, in __fetch_tasks
    for project_id in project_ids]
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/phabricator.py", line 155, in <listcomp>
    for project_id in project_ids]
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/phabricator.py", line 250, in __get_or_fetch_project
    project = self.__fetch_and_parse_phids(project_id)[0]
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/phabricator.py", line 316, in __fetch_and_parse_phids
    return [phid for phid in result]
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/phabricator.py", line 316, in <listcomp>
    return [phid for phid in result]
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/phabricator.py", line 452, in parse_phids
    for phid in results['result'].values():
AttributeError: 'list' object has no attribute 'values'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/perceval", line 192, in <module>
    main()
  File "/usr/local/bin/perceval", line 110, in main
    cmd.run()
  File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 319, in run
    raise RuntimeError(str(e))
RuntimeError: 'list' object has no attribute 'values'
```
Can you have a look?

**Comment by valeriocos** [comment]
The issue appears when retrieving projects information associated to a task, for instance in:
- https://phabricator.bitergia.net/T2810
- https://phabricator.bitergia.net/T287 

As can be seen from the examples above, one project has restricted access. Thus it seems that the issue is  related to the permission granted to the token used to fetch the data.

**Comment by acs** [comment]
@albertinisg could you retry with the master version of perceval that now includes the @valeriocos fix?

**Comment by albertinisg** [comment]
It works. Thanks @valeriocos !!
