### ISSUE TITLE
[meetup] Meetup rate limit exceeded; 4.0 seconds to rate reset

### ISSUE THREAD

**Issue by acs** [grimoirelab/perceval#183]
It seems that the Meetup API has a new restriction not supported by the current perceval backend.

```
(acs@dellx) ~ $ perceval -g meetup -t XXXX South-East-Puppet-User-Group
....
[2017-10-16 19:33:13,191 - perceval.backends.core.meetup - DEBUG] - Meetup client calls resource: South-East-Puppet-User-Group/events/qsvjncyrdbqb/comments params: {'sign': ('true',), 'key': 'XXXXXXX', 'page': 200}
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.1-py3.5.egg/perceval/backend.py", line 310, in run
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.1-py3.5.egg/perceval/backend.py", line 360, in decorator
    for data in func(self, *args, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.1-py3.5.egg/perceval/backends/core/meetup.py", line 118, in fetch
    event['comments'] = self.__fetch_and_parse_comments(event_id)
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.1-py3.5.egg/perceval/backends/core/meetup.py", line 206, in __fetch_and_parse_comments
    for raw_page in raw_pages:
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.1-py3.5.egg/perceval/backends/core/meetup.py", line 411, in comments
    for page in self._fetch(resource, params):
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.1-py3.5.egg/perceval/backends/core/meetup.py", line 463, in _fetch
    seconds_to_reset=self.rate_limit_reset_ts)
perceval.errors.RateLimitError: Meetup rate limit exceeded; 4.0 seconds to rate reset

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/perceval", line 4, in <module>
    __import__('pkg_resources').run_script('perceval==0.9.1', 'perceval')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.1-py3.5.egg/EGG-INFO/scripts/perceval", line 193, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.1-py3.5.egg/EGG-INFO/scripts/perceval", line 111, in main
    cmd.run()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.1-py3.5.egg/perceval/backend.py", line 319, in run
    raise RuntimeError(str(e))
RuntimeError: Meetup rate limit exceeded; 4.0 seconds to rate reset

```

**Comment by acs** [comment]
There is a flag to sleep when the rate is exhausted:

```
(acs@dellx) ~ $ perceval -g meetup --sleep-for-rate -t XXXX South-East-Puppet-User-Group
...

```

This fixes then issue, Probably this flag should be enabled by default. In any case, I will close this ticket. Thanks @valeriocos for detecting this config option!

**Comment by albertinisg** [comment]
Even using the flag, the issue happens:
```bash
2017-11-06 22:33:04,416 - grimoire_elk.arthur - ERROR - Error feeding ocean from meetup (https://meetup.com/): 429 Client Error: Too Many Requests for url: https://api.meetup.com/oc-rust/events?fields=event_hosts,featured,group_topics,plain_text_description,rsvpable,seriesu0026status=cancelled,upcoming,past,proposed,suggested,draftu0026sign=trueu0026order=updatedu0026scroll=since%3A2017-11-02T17%3A07%3A47.000Zu0026page=200u0026key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Traceback (most recent call last):
  File "./grimoire_elk/arthur.py", line 130, in feed_backend
    ocean_backend.feed()
  File "./grimoire_elk/ocean/elastic.py", line 201, in feed
    for item in items:
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.1-py3.4.egg/perceval/backend.py", line 360, in decorator
    for data in func(self, *args, **kwargs):
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.1-py3.4.egg/perceval/backends/core/meetup.py", line 110, in fetch
    for evp in ev_pages:
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.1-py3.4.egg/perceval/backends/core/meetup.py", line 399, in events
    for page in self._fetch(resource, params):
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.1-py3.4.egg/perceval/backends/core/meetup.py", line 466, in _fetch
    r.raise_for_status()
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 937, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.meetup.com/oc-rust/events?fields=event_hosts,featured,group_topics,plain_text_description,rsvpable,seriesu0026status=cancelled,upcoming,past,proposed,suggested,draftu0026sign=trueu0026order=updatedu0026scroll=since%3A2017-11-02T17%3A07%3A47.000Zu0026page=200u0026key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

**Comment by acs** [comment]
@valeriocos could you take a look?

**Comment by valeriocos** [comment]
sure @acs

**Comment by valeriocos** [comment]
I've prepared a fix (similar to what has been done for throttled requests in Github). However, I'm not able to replicate the error (I have tried to call the Meetup backend on **oc-rust**).
Could you confirm that the Meetup group is **oc-rust** or tell me the group where the error happens?

Thanks

**Comment by albertinisg** [comment]
We are fetching many groups at the same time, afaik, iteratively; but @acs should confirm how this is implemented in GELK. Find the full list of groups [here](https://github.com/Bitergia/projects-mozilla/blob/master/projects.json#L3001) (I was unable to reproduce just with perceval either)

**Comment by sduenas** [comment]
@valeriocos maybe you should try with different instances of perceval running at the same time to reproduce the error. The solution would be to stop the execution for some secs.

In any case, @albertinisg, you should control how many instances of perceval you run at the same time fetching data from Meetup. Do not overhead their system, please.
