### ISSUE TITLE
Perceval crashing on reactions

### ISSUE THREAD

**Issue by TheReal1604** [grimoirelab/perceval#187]
```
>>> perceval github jitsi jitsi-meet
[2017-10-24 19:26:35,000] - Sir Perceval is on his quest.
[2017-10-24 19:26:35,463] - Getting info for https://api.github.com/users/emcho
[2017-10-24 19:26:35,659] - Getting info for https://api.github.com/users/fippo
Traceback (most recent call last):
  File "/home/perceval/.local/lib/python3.5/site-packages/perceval/backend.py", line 310, in run
    for item in items:
  File "/home/perceval/.local/lib/python3.5/site-packages/perceval/backend.py", line 360, in decorator
    for data in func(self, *args, **kwargs):
  File "/home/perceval/.local/lib/python3.5/site-packages/perceval/backends/core/github.py", line 175, in fetch
    issue[field + '_data'] = self.__get_issue_comments(issue['number'])
  File "/home/perceval/.local/lib/python3.5/site-packages/perceval/backends/core/github.py", line 280, in __get_issue_comments
    self.__get_issue_comment_reactions(comment_id, comment['reactions']['total_count'])
KeyError: 'reactions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/perceval", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/perceval/arthur/src/perceval/bin/perceval", line 193, in <module>
    main()
  File "/home/perceval/arthur/src/perceval/bin/perceval", line 111, in main
    cmd.run()
  File "/home/perceval/.local/lib/python3.5/site-packages/perceval/backend.py", line 319, in run
    raise RuntimeError(str(e))
RuntimeError: 'reactions'

```
Installed perceval like documented from source code, any idea what is going wrong?

**Comment by valeriocos** [comment]
sure @acs

**Comment by valeriocos** [comment]
@TheReal1604 thanks for reporting the issue.
If you provide a token, you will be able to extract the reactions smoothly.

**Comment by TheReal1604** [comment]
Good to know! Thanks for the hint. I try it again with a token next time. 😜
