### ISSUE TITLE
[jenkins] Connection timed out issue

### ISSUE THREAD

**Issue by albertinisg** [grimoirelab/perceval#197]
Getting Jenkins data from https://build.opnfv.org/ci/ we are getting connection timeout issues many times:
```
2017-11-07 08:09:04,306 - grimoire_elk.arthur - ERROR - Error feeding ocean from jenkins (https://build.opnfv.org/ci): HTTPSConnectionPool(host='build.opnfv.org', port=443): Max retries exceeded with url: /ci/job/apex-testsuite-os-nosdn-fdio-noha-baremetal-master/api/json?depth=2 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fbac4c43860>: Failed to establish a new connection: [Errno 110] Connection timed out',))
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/local/lib/python3.4/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fbac4c43860>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.4/dist-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='build.opnfv.org', port=443): Max retries exceeded with url: /ci/job/apex-testsuite-os-nosdn-fdio-noha-baremetal-master/api/json?depth=2 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fbac4c43860>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./grimoire_elk/arthur.py", line 130, in feed_backend
    ocean_backend.feed()
  File "./grimoire_elk/ocean/elastic.py", line 204, in feed
    for item in items:
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.3-py3.4.egg/perceval/backend.py", line 360, in decorator
    for data in func(self, *args, **kwargs):
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.3-py3.4.egg/perceval/backends/core/jenkins.py", line 86, in fetch
    raw_builds = self.client.get_builds(job['name'])
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.3-py3.4.egg/perceval/backends/core/jenkins.py", line 218, in get_builds
    req = requests.get(url_jenkins)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='build.opnfv.org', port=443): Max retries exceeded with url: /ci/job/apex-testsuite-os-nosdn-fdio-noha-baremetal-master/api/json?depth=2 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fbac4c43860>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```
I did speak with @acs as I thought that GELK should be aware of handling this kind of issues, but it seems impossible:

>> @acs wrote:
>
> @albertinisg some retry logic is done in GELK but there are logic that can not be done from GELK because the queries to be retried are only known by perceval.

**Comment by sduenas** [comment]
@valeriocos can you have a look to this? Same logic used in other clients would be valid for this backend too.

**Comment by sduenas** [comment]
It should be fixed now. The solution was to resend the request but maybe this doesn't fix the problem propertly because it might be a problem in the server, that lasts too long generating the response.

Feel free to reopen it if the problem persists.
