### ISSUE TITLE
[pipermail] Compressed file ended before the end-of-stream marker was reached

### ISSUE THREAD

**Issue by acs** [grimoirelab/perceval#209]
Trying to analyze the pipermail url:

```
(acs@dellx) ~ $ perceval -g pipermail http://lists.openshift.redhat.com/openshift-archives/dev/
.....
    "origin": "http://lists.openshift.redhat.com/openshift-archives/dev/",
    "perceval_version": "0.9.4",
    "tag": "http://lists.openshift.redhat.com/openshift-archives/dev/",
    "timestamp": 1510779260.043333,
    "updated_on": 1359665232.0,
    "uuid": "cc8e796d1d6d3adb7a791404b2399463e7b4e34b"
}
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.4-py3.5.egg/perceval/backend.py", line 310, in run
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.4-py3.5.egg/perceval/backend.py", line 360, in decorator
    for data in func(self, *args, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.4-py3.5.egg/perceval/backends/core/pipermail.py", line 92, in fetch
    for message in messages:
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.4-py3.5.egg/perceval/backends/core/mbox.py", line 138, in _fetch_and_parse_messages
    raise e
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.4-py3.5.egg/perceval/backends/core/mbox.py", line 108, in _fetch_and_parse_messages
    tmp_path = self._copy_mbox(mbox)
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.4-py3.5.egg/perceval/backends/core/mbox.py", line 153, in _copy_mbox
    for l in f_in:
  File "/usr/lib/python3.5/gzip.py", line 372, in readline
    return self._buffer.readline(size)
  File "/usr/lib/python3.5/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.5/gzip.py", line 480, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/perceval", line 4, in <module>
    __import__('pkg_resources').run_script('perceval==0.9.4', 'perceval')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.4-py3.5.egg/EGG-INFO/scripts/perceval", line 193, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.4-py3.5.egg/EGG-INFO/scripts/perceval", line 111, in main
    cmd.run()
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.9.4-py3.5.egg/perceval/backend.py", line 319, in run
    raise RuntimeError(str(e))
RuntimeError: Compressed file ended before the end-of-stream marker was reached
```

Not sure if there is a corrupted file in the archive, or there is a problem downloading it.

Checking the downloaded files:

```
(acs@dellx) ~/.perceval/mailinglists/http:/lists.openshift.redhat.com/openshift-archives/dev $ gunzip *
gzip: 2013-April.txt.gz: invalid compressed data--crc error

gzip: 2013-April.txt.gz: invalid compressed data--length error

```

**Comment by valeriocos** [comment]
This issue is fixed by [PR 311](https://github.com/grimoirelab/perceval/pull/311)
