### ISSUE TITLE
^M) in git logs causing trouble

### ISSUE THREAD

**Issue by jgbarah** [grimoirelab/perceval#21]
In some messages from the Linux kernel git log, the following line appears:

```
    ^M)
```

That is, four spaces followed by ASCII 13, Carriage Return, a parenthesis and the end of line. See an example of a one-commit git log with one of these commits in
[linux-gitlog.txt](https://github.com/grimoirelab/perceval/files/178808/linux-gitlog.txt) (line 9 in that file).

The regex in perceval/backends/git.py for parsing the message is looking for lines starting with four spaces:

``` python
    MESSAGE_LINE_PATTERN = r"[\s]{4}(?P<msg>.*)$"
```

But this fails miserably in this case: the CR is identified by the regex as the end of the line ($), and the reminding parenthesis as the beginning of the next line. Since that one does not start with four spaces (in fact, it starts with "(", it is not considered as a message line, and therefore the message ends. This causes the code to consider the commit up to this line, and then expect a new commit starting in line 10, which is not happening. Exception launched, end. You can reproduce (using the attached file, saved as /tmp/linux-gitlog.txt) as follows:

```
$ perceval -g git --git-log /tmp/linux-gitlog.txt http://github.com/torvalds/linux.git
[2016-03-17 23:51:36,617 - root - INFO] - Sir Perceval is on his quest.
[2016-03-17 23:51:36,618 - perceval.backends.git - INFO] - Fetching commits: 'http://github.com/torvalds/linux.git' git repository from 1970-01-01 00:00:00+00:00
[2016-03-17 23:51:36,618 - perceval.backends.git - DEBUG] - Invalid message format on line 10. Skipping.
[2016-03-17 23:51:36,619 - perceval.backends.git - DEBUG] - Invalid action format on line 10. Skipping.
[2016-03-17 23:51:36,619 - perceval.backends.git - DEBUG] - Commit 2d137c24e9f433e37ffd10b3d5f418157589a8d2 parsed
{
    "Author": "akpm@osdl.org <akpm@osdl.org>",
    "AuthorDate": "Sat Apr 16 15:23:55 2005 -0700",
    "Commit": "Linus Torvalds <torvalds@ppc970.osdl.org>",
    "CommitDate": "Sat Apr 16 15:23:55 2005 -0700",
    "__metadata__": {
        "backend_name": "Git",
        "backend_version": "0.1.0",
        "origin": "http://github.com/torvalds/linux.git",
        "timestamp": 1458255096.619283,
        "updated_on": 1113690235.0
    },
    "commit": "2d137c24e9f433e37ffd10b3d5f418157589a8d2",
    "files": [],
    "message": "[PATCH] arm: fix SIGBUS handling\n\n",
    "parents": [
        "baaa2c512dc1c47e3afeb9d558c5323c9240bd21"
    ],
    "refs": []
}
Traceback (most recent call last):
  File "/home/jgb/venvs/grimoirelab/lib/python3.5/site-packages/perceval/backends/git.py", line 204, in run
    for commit in commits:
  File "/home/jgb/venvs/grimoirelab/lib/python3.5/site-packages/perceval/backend.py", line 161, in decorator
    for item in func(self, *args, **kwargs):
  File "/home/jgb/venvs/grimoirelab/lib/python3.5/site-packages/perceval/backends/git.py", line 107, in fetch
    for commit in commits:
  File "/home/jgb/venvs/grimoirelab/lib/python3.5/site-packages/perceval/backends/git.py", line 150, in parse_git_log_from_file
    for commit in parser.parse():
  File "/home/jgb/venvs/grimoirelab/lib/python3.5/site-packages/perceval/backends/git.py", line 371, in parse
    parsed = self.handlers[self.state](line)
  File "/home/jgb/venvs/grimoirelab/lib/python3.5/site-packages/perceval/backends/git.py", line 413, in _handle_commit
    raise ParseError(cause=msg)
perceval.errors.ParseError: commit expected on line 10

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jgb/venvs/grimoirelab/bin/perceval", line 163, in <module>
    main()
  File "/home/jgb/venvs/grimoirelab/bin/perceval", line 84, in main
    cmd.run()
  File "/home/jgb/venvs/grimoirelab/lib/python3.5/site-packages/perceval/backends/git.py", line 211, in run
    raise RuntimeError(str(e))
RuntimeError: commit expected on line 10
```

I guess the regex should be fixed to consider this case, or maybe CR should be filtered out somehow before using the regex.

**Comment by jgbarah** [comment]
After some more detailed inspection, the problem is not with the regex, but with the way the log file is parsed in lines. The code is [line 375 perceval/backends/git.py](https://github.com/grimoirelab/perceval/blob/master/perceval/backends/git.py#L375):

```python
    def parse(self):
        """Parse the Git log stream."""

        for line in self.stream:
            line = line.rstrip('\n')
            parsed = False
            self.nline += 1
```

When getting the lines from the stream in the for loop, it seems that if the line includes CR, it is considered as two lines (one before CR, another one after). That can be seen easily by adding a print statement:

```python
        for line in self.stream:
            line = line.rstrip('\n')
            print ("Line: " + line + ".")
            parsed = False
            self.nline += 1
```

When running this through perceval with the line in the previous comment, I get the following output:

```
Line: commit 2d137c24e9f433e37ffd10b3d5f418157589a8d2 baaa2c512dc1c47e3afeb9d558c5323c9240bd21.
Line: Author:     akpm@osdl.org <akpm@osdl.org>.
Line: AuthorDate: Sat Apr 16 15:23:55 2005 -0700.
Line: Commit:     Linus Torvalds <torvalds@ppc970.osdl.org>.
Line: CommitDate: Sat Apr 16 15:23:55 2005 -0700.
Line: .
Line:     [PATCH] arm: fix SIGBUS handling.
Line:     .
Line:     .
Line: ).
```

That is, the CR just before the ")" was considered by the for loop as a line end.

Therefore, to fix this we need to be more clever when breaking the stream in lines in the for loop.

**Comment by jgbarah** [comment]
I guess I found a fix. In Python3, there is an argument for open, which allows to specify the newline to use when splitting in lines. In perceval/backends/git, this is in line 147. The following text;

```python
        with open(filepath, 'r', errors='surrogateescape') as f:
            parser = GitParser(f)

            for commit in parser.parse():
                yield commit
```

should be changed to:

```python
        with open(filepath, 'r', errors='surrogateescape', newline = os.linesep) as f:
            parser = GitParser(f)

            for commit in parser.parse():
                yield commit
```

That is, adding "newline = os.linesep". This parameter [specifies the characters to be used as newline](https://docs.python.org/release/3.2/library/functions.html#open). os.linesep is the "operating system newline". In Linux it is "\n", in Windows "\r\n", in (old) Mac, "\r". So this trick maybe won't work in old Macs, but for those, I don't see how to fix the issue...

Of course, this assume that the git log file was created in our architecture. Since this maybe not the case, maybe this should be a configurable parameter, I don't know. But for now, I guess the fix should work.

Please, let me know if this would be a good fix:: I can produce a pull request if needed.

**Comment by jgbarah** [comment]
I see that in other cases, the git backend is using "\n" instead of os.linesep for splitting in lines. So, maybe it would be better to either use always "\n", or always os.linesep.
