### ISSUE TITLE
Fetch process fails when `latest-items` is set and 'git://' protocol is used

### ISSUE THREAD

**Issue by sduenas** [grimoirelab/perceval#210]
This error can be reproduced after `perceval` runs successfully the first time. The second time, when `latest-items` flag comes in play, the library is unable find the service.

Some examples:

* OpenEmbedded
```
$ perceval -g git --latest-items --git-path /tmp/openembedded-core git://git.openembedded.org/openembedded-core

[2017-11-22 11:51:08,095 - root - INFO] - Sir Perceval is on his quest.
[2017-11-22 11:51:08,097 - perceval.backends.core.git - INFO] - Fetching latest commits: 'git://git.openembedded.org/openembedded-core' git repository
Traceback (most recent call last):
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.4-py3.5.egg/perceval/backend.py", line 310, in run
    for item in items:
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.4-py3.5.egg/perceval/backend.py", line 360, in decorator
    for data in func(self, *args, **kwargs):
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.4-py3.5.egg/perceval/backends/core/git.py", line 120, in fetch
    latest_items)
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.4-py3.5.egg/perceval/backends/core/git.py", line 146, in __fetch_from_repo
    commits = self.__fetch_newest_commits_from_repo(repo)
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.4-py3.5.egg/perceval/backends/core/git.py", line 177, in __fetch_newest_commits_from_repo
    hashes = repo.sync()
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.4-py3.5.egg/perceval/backends/core/git.py", line 867, in sync
    pack_name, refs = self._fetch_pack()
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.4-py3.5.egg/perceval/backends/core/git.py", line 1012, in _fetch_pack
    fd.write)
  File "/home/sduenas/.local/lib/python3.5/site-packages/dulwich/client.py", line 727, in fetch_pack
    proto, can_read = self._connect(b'upload-pack', path)
  File "/home/sduenas/.local/lib/python3.5/site-packages/dulwich/client.py", line 814, in _connect
    self._host, self._port, socket.AF_UNSPEC, socket.SOCK_STREAM)
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sduenas/.local/bin/perceval", line 4, in <module>
    __import__('pkg_resources').run_script('perceval==0.9.4', 'perceval')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.4-py3.5.egg/EGG-INFO/scripts/perceval", line 193, in <module>
    main()
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.4-py3.5.egg/EGG-INFO/scripts/perceval", line 111, in main
    cmd.run()
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.4-py3.5.egg/perceval/backend.py", line 315, in run
    raise RuntimeError(str(e))
RuntimeError: [Errno -2] Name or service not known
```

* Perceval
```
sduenas@Guybrush:/tmp$ perceval -g git --latest-items --git-path /tmp/perceval git://github.com/grimoirelab/perceval
[2017-11-22 11:58:40,746 - root - INFO] - Sir Perceval is on his quest.
[2017-11-22 11:58:40,748 - perceval.backends.core.git - INFO] - Fetching latest commits: 'git://github.com/grimoirelab/perceval' git repository
Traceback (most recent call last):
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.4-py3.5.egg/perceval/backend.py", line 310, in run
    for item in items:
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.4-py3.5.egg/perceval/backend.py", line 360, in decorator
    for data in func(self, *args, **kwargs):
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.4-py3.5.egg/perceval/backends/core/git.py", line 120, in fetch
    latest_items)
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.4-py3.5.egg/perceval/backends/core/git.py", line 146, in __fetch_from_repo
    commits = self.__fetch_newest_commits_from_repo(repo)
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.4-py3.5.egg/perceval/backends/core/git.py", line 177, in __fetch_newest_commits_from_repo
    hashes = repo.sync()
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.4-py3.5.egg/perceval/backends/core/git.py", line 867, in sync
    pack_name, refs = self._fetch_pack()
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.4-py3.5.egg/perceval/backends/core/git.py", line 1012, in _fetch_pack
    fd.write)
  File "/home/sduenas/.local/lib/python3.5/site-packages/dulwich/client.py", line 727, in fetch_pack
    proto, can_read = self._connect(b'upload-pack', path)
  File "/home/sduenas/.local/lib/python3.5/site-packages/dulwich/client.py", line 814, in _connect
    self._host, self._port, socket.AF_UNSPEC, socket.SOCK_STREAM)
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sduenas/.local/bin/perceval", line 4, in <module>
    __import__('pkg_resources').run_script('perceval==0.9.4', 'perceval')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.4-py3.5.egg/EGG-INFO/scripts/perceval", line 193, in <module>
    main()
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.4-py3.5.egg/EGG-INFO/scripts/perceval", line 111, in main
    cmd.run()
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.4-py3.5.egg/perceval/backend.py", line 315, in run
    raise RuntimeError(str(e))
RuntimeError: [Errno -2] Name or service not known
```

This bug is related to grimoirelab/grimoirelab#39

**Comment by sduenas** [comment]
This exception is raised because the url used to initialize the `dulwich` client client is wrong.
