### ISSUE TITLE
AttributeError: class Backend has no attribute '__subclasses__'

### ISSUE THREAD

**Issue by hisi91** [grimoirelab/perceval#221]
I can't run my command line, I got this error every time I run this line: 

Traceback (most recent call last):
  File "/home/spark/anaconda/bin/perceval", line 193, in <module>     main()
 File "/home/spark/anaconda/bin/perceval", line 100, in main
    _, PERCEVAL_CMDS = perceval.find_backends(perceval.backends)
  File "/home/spark/anaconda/lib/python2.7/site-packages/perceval/backend.py", line 425, in find_backends
    return _import_backends(modules)
  File "/home/spark/anaconda/lib/python2.7/site-packages/perceval/backend.py", line 432, in _import_backends
    bkls = _filter_classes(Backend.__subclasses__(), modules)
AttributeError: class Backend has no attribute '__subclasses__'

**Comment by sduenas** [comment]
Perceval doesn't run with Python 2.7. It's Python3. Your problem is related to that. Classes in Python2.7 don't have that method, by default.

Make sure you install and run it using Python3.

I close it as invalid.
