### ISSUE TITLE
[perceval-client] 406 Not acceptable URL

### ISSUE THREAD

**Issue by albertinisg** [grimoirelab/perceval#243]
Using the latest perceval version 17d9cb891fed0c5cf584d9a370021ef48190115c, it returns 406 Not acceptable URL for DockerHub and JIRA:

```
2017-12-05 08:03:04,045 - grimoire_elk.arthur - ERROR - Error feeding ocean from dockerhub (https://hub.docker.com/confluent/rest-proxy): 406 Client Error: NOT ACCEPTABLE for url: https://hub.docker.com/v2/repositories/confluent/rest-proxy/
Traceback (most recent call last):
  File "./grimoire_elk/arthur.py", line 134, in feed_backend
    ocean_backend.feed()
  File "./grimoire_elk/ocean/elastic.py", line 203, in feed
    for item in items:
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.7-py3.4.egg/perceval/backend.py", line 360, in decorator
    for data in func(self, *args, **kwargs):
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.7-py3.4.egg/perceval/backends/core/dockerhub.py", line 92, in fetch
    raw_data = self.client.repository(self.owner, self.repository)
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.7-py3.4.egg/perceval/backends/core/dockerhub.py", line 207, in repository
    response = self.fetch(url)
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.7-py3.4.egg/perceval/client.py", line 122, in fetch
    response.raise_for_status()
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 406 Client Error: NOT ACCEPTABLE for url: https://hub.docker.com/v2/repositories/confluent/rest-proxy/
```

EDIT: same behavior in JIRA backend:
```
2017-12-05 08:03:04,269 - grimoire_elk.arthur - ERROR - Error feeding ocean from jira (https://issues.apache.org/jira): 406 Client Error: Not Acceptable for url: https://issues.apache.org/jira/rest/api/2/field
Traceback (most recent call last):
  File "./grimoire_elk/arthur.py", line 134, in feed_backend
    ocean_backend.feed()
  File "./grimoire_elk/ocean/elastic.py", line 203, in feed
    for item in items:
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.7-py3.4.egg/perceval/backend.py", line 360, in decorator
    for data in func(self, *args, **kwargs):
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.7-py3.4.egg/perceval/backends/core/jira.py", line 142, in fetch
    fields = json.loads(self.client.get_fields())
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.7-py3.4.egg/perceval/backends/core/jira.py", line 354, in get_fields
    req = self.fetch(url)
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.7-py3.4.egg/perceval/client.py", line 122, in fetch
    response.raise_for_status()
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 406 Client Error: Not Acceptable for url: https://issues.apache.org/jira/rest/api/2/field
```

**Comment by valeriocos** [comment]
I'm not able to replicate the error in my machine. 
I found an [issue](https://github.com/misja/python-boilerpipe/issues/24) similar to the one you are reporting, the 406 error may be related to a problem in the user-agent header. Thus, I've just sent a PR (#245) which sets the user-agent header to the format for automated agents.
