### ISSUE TITLE
[meetup] Too many 429 responses

### ISSUE THREAD

**Issue by albertinisg** [grimoirelab/perceval#247]
Using the latest version, seems we are analyzing too many groups for Meetup, and perceval can't handle all the error responses returned. See the following traceback:
```
2017-12-05 10:09:52,658 - grimoire_elk.arthur - ERROR - Error feeding ocean from meetup (https://meetup.com/): HTTPSConnectionPool(host='api.meetup.com', port=443): Max retries exceeded with url: /Meetup-Rust-Lyon/events?fields=event_hosts,featured,group_topics,plain_text_description,rsvpable,series&status=cancelled,upcoming,past,proposed,suggested,draft&page=200&key=XXXXXXXXXXXXXXXXX&sign=true&scroll=since%3A1970-01-01T00%3A00%3A00.000Z&order=updated (Caused by ResponseError('too many 429 error responses',))
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.4/dist-packages/urllib3-1.22-py3.4.egg/urllib3/connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "/usr/local/lib/python3.4/dist-packages/urllib3-1.22-py3.4.egg/urllib3/connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "/usr/local/lib/python3.4/dist-packages/urllib3-1.22-py3.4.egg/urllib3/connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "/usr/local/lib/python3.4/dist-packages/urllib3-1.22-py3.4.egg/urllib3/connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "/usr/local/lib/python3.4/dist-packages/urllib3-1.22-py3.4.egg/urllib3/connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "/usr/local/lib/python3.4/dist-packages/urllib3-1.22-py3.4.egg/urllib3/connectionpool.py", line 712, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/local/lib/python3.4/dist-packages/urllib3-1.22-py3.4.egg/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.meetup.com', port=443): Max retries exceeded with url: /Meetup-Rust-Lyon/events?fields=event_hosts,featured,group_topics,plain_text_description,rsvpable,series&status=cancelled,upcoming,past,proposed,suggested,draft&page=200&key=XXXXXXXXXXXXXXXXXXX&sign=true&scroll=since%3A1970-01-01T00%3A00%3A00.000Z&order=updated (Caused by ResponseError('too many 429 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./grimoire_elk/arthur.py", line 134, in feed_backend
    ocean_backend.feed()
  File "./grimoire_elk/ocean/elastic.py", line 203, in feed
    for item in items:
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.7-py3.4.egg/perceval/backend.py", line 360, in decorator
    for data in func(self, *args, **kwargs):
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.7-py3.4.egg/perceval/backends/core/meetup.py", line 114, in fetch
    for evp in ev_pages:
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.7-py3.4.egg/perceval/backends/core/meetup.py", line 402, in events
    for page in self._fetch(resource, params):
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.7-py3.4.egg/perceval/backends/core/meetup.py", line 458, in _fetch
    r = self.fetch(url, payload=params)
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.7-py3.4.egg/perceval/client.py", line 118, in fetch
    response = self.session.get(url, params=payload, headers=headers, stream=stream, verify=verify)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 499, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.meetup.com', port=443): Max retries exceeded with url: /Meetup-Rust-Lyon/events?fields=event_hosts,featured,group_topics,plain_text_description,rsvpable,series&status=cancelled,upcoming,past,proposed,suggested,draft&page=200&key=XXXXXXXXXXXXXXXXXXXXX&sign=true&scroll=since%3A1970-01-01T00%3A00%3A00.000Z&order=updated (Caused by ResponseError('too many 429 error responses',))
```

**Comment by valeriocos** [comment]
The best option at the moment is to play with the **sleep-time** parameter and find an optimal value to get rid of the 429 HTTP error. In the next days, I'll do some tests to identify a good value for **sleep-time**, but I need to know if the token is used by more than one perceval at the same time.

**Comment by valeriocos** [comment]
Perceval is already doing the best effort reissuing requests in case of connection failures, but it cannot be tailored to specific service limitations (like the meetup API).
This seems to be an issue related to scheduling, because you are running several Perceval processes at the same time. Thus, it should be handled by the components dealing with it (Arthur, Mordred, etc.).

**Comment by valeriocos** [comment]
@acs, do you have any idea to handle this issue?
