### ISSUE TITLE
[git] --latest-items fails in the first retrieval for a repository

### ISSUE THREAD

**Issue by albertinisg** [grimoirelab/perceval#260]
The first collection of a git repository using "--latest-items" doesn't work:
```bash
$ perceval git https://gerrit.onosproject.org/onos-gerrit-base --latest-items
[2017-12-21 21:30:16,880] - Sir Perceval is on his quest.
[2017-12-21 21:30:16,884] - Fetching latest commits: 'https://gerrit.onosproject.org/onos-gerrit-base' git repository
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.8-py3.4.egg/perceval/backend.py", line 310, in run
    for item in items:
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.8-py3.4.egg/perceval/backend.py", line 360, in decorator
    for data in func(self, *args, **kwargs):
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.8-py3.4.egg/perceval/backends/core/git.py", line 118, in fetch
    latest_items)
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.8-py3.4.egg/perceval/backends/core/git.py", line 144, in __fetch_from_repo
    commits = self.__fetch_newest_commits_from_repo(repo)
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.8-py3.4.egg/perceval/backends/core/git.py", line 175, in __fetch_newest_commits_from_repo
    hashes = repo.sync()
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.8-py3.4.egg/perceval/backends/core/git.py", line 865, in sync
    pack_name, refs = self._fetch_pack()
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.8-py3.4.egg/perceval/backends/core/git.py", line 989, in _fetch_pack
    local_refs = [ref.hash.encode('utf-8') for ref in self._discover_refs()
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.8-py3.4.egg/perceval/backends/core/git.py", line 1075, in _discover_refs
    env=self.gitenv)
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.8-py3.4.egg/perceval/backends/core/git.py", line 1204, in _exec
    raise RepositoryError(cause=cause)
perceval.errors.RepositoryError: git command - 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/perceval", line 4, in <module>
    __import__('pkg_resources').run_script('perceval==0.9.8', 'perceval')
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.8-py3.4.egg/EGG-INFO/scripts/perceval", line 193, in <module>
    main()
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.8-py3.4.egg/EGG-INFO/scripts/perceval", line 111, in main
    cmd.run()
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.8-py3.4.egg/perceval/backend.py", line 319, in run
    raise RuntimeError(str(e))
RuntimeError: git command -
```
But it works without the flag:
```bash
$ perceval git https://gerrit.onosproject.org/onos-gerrit-base > /dev/null
[2017-12-21 21:31:51,220] - Sir Perceval is on his quest.
[2017-12-21 21:31:51,225] - Fetching commits: 'https://gerrit.onosproject.org/onos-gerrit-base' git repository from 1970-01-01 00:00:00+00:00; all branches
[2017-12-21 21:31:51,889] - Fetch process completed: 4 commits fetched
[2017-12-21 21:31:51,892] - Sir Perceval completed his quest.
```

**Comment by sduenas** [comment]
Running it in debug mode, we can see the command is failing is `git show-ref`

```
$ perceval -g git https://gerrit.onosproject.org/onos-gerrit-base --latest-items
[2017-12-22 00:23:15,902 - root - INFO] - Sir Perceval is on his quest.
[2017-12-22 00:23:15,904 - perceval.backends.core.git - INFO] - Fetching latest commits: 'https://gerrit.onosproject.org/onos-gerrit-base' git repository
[2017-12-22 00:23:15,905 - perceval.backends.core.git - DEBUG] - Running command git count-objects -v (cwd: /home/sduenas/.perceval/repositories/https://gerrit.onosproject.org/onos-gerrit-base-git, env: {'HOME': '/home/sduenas', 'LANG': 'C', 'PAGER': ''})
[2017-12-22 00:23:15,908 - perceval.backends.core.git - DEBUG] - 
[2017-12-22 00:23:15,908 - perceval.backends.core.git - DEBUG] - Git https://gerrit.onosproject.org/onos-gerrit-base repository has 19 objects
[2017-12-22 00:23:15,908 - perceval.backends.core.git - DEBUG] - Running command git show-ref --heads --tags (cwd: /home/sduenas/.perceval/repositories/https://gerrit.onosproject.org/onos-gerrit-base-git, env: {'HOME': '/home/sduenas', 'LANG': 'C', 'PAGER': ''})
Traceback (most recent call last):
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.7-py3.5.egg/perceval/backend.py", line 310, in run
    for item in items:
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.7-py3.5.egg/perceval/backend.py", line 360, in decorator
    for data in func(self, *args, **kwargs):
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.7-py3.5.egg/perceval/backends/core/git.py", line 118, in fetch
    latest_items)
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.7-py3.5.egg/perceval/backends/core/git.py", line 144, in __fetch_from_repo
    commits = self.__fetch_newest_commits_from_repo(repo)
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.7-py3.5.egg/perceval/backends/core/git.py", line 175, in __fetch_newest_commits_from_repo
    hashes = repo.sync()
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.7-py3.5.egg/perceval/backends/core/git.py", line 865, in sync
    pack_name, refs = self._fetch_pack()
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.7-py3.5.egg/perceval/backends/core/git.py", line 989, in _fetch_pack
    local_refs = [ref.hash.encode('utf-8') for ref in self._discover_refs()
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.7-py3.5.egg/perceval/backends/core/git.py", line 1075, in _discover_refs
    env=self.gitenv)
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.7-py3.5.egg/perceval/backends/core/git.py", line 1204, in _exec
    raise RepositoryError(cause=cause)
perceval.errors.RepositoryError: git command - 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sduenas/.local/bin/perceval", line 4, in <module>
    __import__('pkg_resources').run_script('perceval==0.9.7', 'perceval')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.7-py3.5.egg/EGG-INFO/scripts/perceval", line 193, in <module>
    main()
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.7-py3.5.egg/EGG-INFO/scripts/perceval", line 111, in main
    cmd.run()
  File "/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.9.7-py3.5.egg/perceval/backend.py", line 319, in run
    raise RuntimeError(str(e))
RuntimeError: git command -
```
If we run this command, we can see it returns `1` as error code. According to the [documentation](https://git-scm.com/docs/git-show-ref#_example), this error code is returned when no references match with the input. In this case, that means there aren't  `refs/heads` nor `refs/tags` references.

```
$ git show-ref --heads --tags
$ echo $?
1
```

**Comment by sduenas** [comment]
Fixed
