### ISSUE TITLE
ImportError: No module named 'dateutil'

### ISSUE THREAD

**Issue by brylie** [grimoirelab/perceval#27]
On a new Perceval installaiton, I get the following error when running the script:

```py
Traceback (most recent call last):
  File "/usr/local/bin/perceval", line 30, in <module>
    from perceval.backends import PERCEVAL_CMDS
  File "/usr/local/lib/python3.4/dist-packages/perceval/backends/__init__.py", line 23, in <module>
    from .bugzilla import Bugzilla, BugzillaCommand
  File "/usr/local/lib/python3.4/dist-packages/perceval/backends/bugzilla.py", line 32, in <module>
    import dateutil.tz
ImportError: No module named 'dateutil'
```
When I attempt to install python3-dateutil, I get the following messages:

```bash
$ sudo pip3 install python-dateutil
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/local/lib/python3.4/dist-packages
```

```bash
sudo pip3 install python-dateutil --upgrade
Requirement already up-to-date: python-dateutil in /usr/local/lib/python3.4/dist-packages
```
# Solution
I was able to fix this message by using the APT package:

```
sudo apt-get install python3-dateutil
```

**Comment by gpoo** [comment]
This is the same as issue #26
