### ISSUE TITLE
Python3 requests issue with Perceval

### ISSUE THREAD

**Issue by robinmuilwijk** [grimoirelab/perceval#44]
When running a command on Perceval, I get errors where python requests: RuntimeError: [SSL: CERTIFICATE_VERIFY_FAILED] . My details are as follows.

Met setup: A Windows 10 machine, with latest Virtualbox, and Suse Leap 42. Python3 is installed with all the required extensions. So far, I only installed Perceval, to see how far I get with this.

I run the following command, which does provide feedback that Perceval is on a quest:

```
$ perceval github -u your_github_user -p your_github_passwd --owner
elastic --repository filebeat --from-date '2016-01-01'
```

However, this throws the following output/errors:

osboxes:/home/osboxes/grimoire # perceval github -u 'robinmuilwijk' -p '********' --owner elastic --repository filebeat --from-date '2016-01-01'
[2016-06-11 11:01:44,037] - Sir Perceval is on his quest.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 279, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib64/python3.4/ssl.py", line 364, in wrap_socket
    _context=self)
  File "/usr/lib64/python3.4/ssl.py", line 578, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.4/ssl.py", line 805, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 367, in send
    timeout=timeout
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 574, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/perceval/backends/github.py", line 409, in run
    for issue in issues:
  File "/usr/lib/python3.4/site-packages/perceval/backend.py", line 171, in decorator
    for data in func(self, *args, **kwargs):
  File "/usr/lib/python3.4/site-packages/perceval/backends/github.py", line 135, in fetch
    for raw_issues in issues_groups:
  File "/usr/lib/python3.4/site-packages/perceval/backends/github.py", line 307, in get_issues
    self.__get_headers())
  File "/usr/lib/python3.4/site-packages/perceval/backends/github.py", line 291, in __send_request
    r = requests.get(url, params=params, headers=headers)
  File "/usr/lib/python3.4/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 428, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/perceval", line 163, in <module>
    main()
  File "/usr/bin/perceval", line 84, in main
    cmd.run()
  File "/usr/lib/python3.4/site-packages/perceval/backends/github.py", line 417, in run
    raise RuntimeError(str(e))
RuntimeError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
osboxes:/home/osboxes/grimoire # 

I tried what you suggested, running the below commands in python console:

```
>>> import requests
>>> requests.get('https://github.com', verify=True)
```

I did the same with url api.github.com but both give me the same errors as I listed above.

So I ended up changing /perceval/backends/github.py at line 291, to:

`r = requests.get(url, params=params, headers=headers, verify=False)`

That does not solve the problem either, same errors again. Did I change that line incorrectly?

Thanks, Robin

**Comment by gpoo** [comment]
In the same virtual machine, do you succeed to open https://github.com ? (that is, is the certificate verified as well?)

It seems to me there is a "Man in the Middle" issue (perhaps a proxy).

**Comment by robinmuilwijk** [comment]
I can indeed open https://github.com, and can see the certificate is verified.

![unnamed](https://cloud.githubusercontent.com/assets/632615/15986995/7804aaa2-3019-11e6-8baa-edbc73924fdc.png)

**Comment by robinmuilwijk** [comment]
I might try Python on Windows, and rule out the VM. I will let you know how that goes.

**Comment by jgbarah** [comment]
Alternatively, you can as well set up a virtualenv environment for python3, and install requests in it (just to see whether that has to do with requests installation or not). See http://docs.python-guide.org/en/latest/dev/virtualenvs/

Given that this:

```
>>> import requests
>>> requests.get('https://github.com', verify=True)
```

gives you the same error, we can discard that the problem is in Perceval, though. I'm labeling it as "question", therefore. In short, my gut feeling is that this is a either a problem with requests installation, or with some kind of proxy in the middle. Could you try

```
>>> import requests
>>> requests.get('https://github.com', verify=False)
```

To see if the problems happens without verification? (if you don't get 200, please paste the log messages).

**Comment by robinmuilwijk** [comment]
The output of that last suggestion is as follows:

```
osboxes@osboxes:~/grimoire> python3
Python 3.4.1 (default, May 23 2014, 17:48:28) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.get('https://github.com', verify=False)
/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
<Response [200]>
>>> 
```

**Comment by robinmuilwijk** [comment]
I was able to setup virtualenv. I also installed the required python modules. Running the requests.get in the python console now give me a response code 200. So the virtualenv does help here.

However, I keep getting an ssl error while running perceval:

```
(tenv) root@osboxes:/home/osboxes/grimoire> perceval github -u 'robinmuilwijk' -p 'Mu1lw!jk' --owner ezsystems --repository ezplatform --from-date '2016-01-01'
[2016-06-12 19:41:09,383] - Sir Perceval is on his quest.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 279, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib64/python3.4/ssl.py", line 364, in wrap_socket
    _context=self)
  File "/usr/lib64/python3.4/ssl.py", line 578, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.4/ssl.py", line 805, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 367, in send
    timeout=timeout
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 574, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/perceval/backends/github.py", line 409, in run
    for issue in issues:
  File "/usr/lib/python3.4/site-packages/perceval/backend.py", line 171, in decorator
    for data in func(self, *args, **kwargs):
  File "/usr/lib/python3.4/site-packages/perceval/backends/github.py", line 135, in fetch
    for raw_issues in issues_groups:
  File "/usr/lib/python3.4/site-packages/perceval/backends/github.py", line 307, in get_issues
    self.__get_headers())
  File "/usr/lib/python3.4/site-packages/perceval/backends/github.py", line 291, in __send_request
    r = requests.get(url, params=params, headers=headers)
  File "/usr/lib/python3.4/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 428, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/perceval", line 163, in <module>
    main()
  File "/usr/bin/perceval", line 84, in main
    cmd.run()
  File "/usr/lib/python3.4/site-packages/perceval/backends/github.py", line 417, in run
    raise RuntimeError(str(e))
RuntimeError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
(tenv) root@osboxes:/home/osboxes/grimoire> 
```

This is running in env:

(tenv) root@osboxes:/home/osboxes/grimoire> pip list
beautifulsoup4 (4.4.1)
bs4 (0.0.1)
pip (8.1.2)
python-dateutil (2.5.3)
requests (2.10.0)
setuptools (23.0.0)
six (1.10.0)
wheel (0.29.0)


The /tenv folder is at the same level as /perceval. Could that be the problem? Should /perceval be inside /tenv?

**Comment by jgbarah** [comment]
I guess this (the output with "verify=False") confirms the problem. As you can see, if the certificate is not verified, requests.get() works. Therefore, I see two solutions here:

* You debug a bit more to see why requests is not verifying the certificate. That's likely due to some problem in the certificate you get (because there is some proxy or something, as @gpoo suggested) or to requests installation (like it doesn't recognize the CA for GitHub). In the end, the fix would be having Python requests in good shape, and/or the communication with GitHub in good shape.

* You amend slightly the code for Perceval, adding that "verify=False" to all requests calls.

Since I cannot reproduce the problem, I guess I cannot help you much more :-(

Maybe this link, about CAs, can be of help: http://docs.python-requests.org/en/master/user/advanced/#ca-certificates

In any case, the fact that a fresh install in a virtualenv works, suggests that maybe the problem is just an outdated CA list.

**Comment by robinmuilwijk** [comment]
Thanks, I will debug a bit more, and let you know any outcome here. If I keep getting stuck, I will move from the VM to Windows, and see how far I get on that.

**Comment by jgbarah** [comment]
With respect to the virtualenv test:: no, it doesn't matter where is the perceval directory. The important thing is that it is run from an "activated" shell (one where you had previously run "source activate" for the virtualenv. From your log, it seems you did this.

Could you run the requests.get() test on https://api.github.io ? I mean, instead of get("https://github.io"), get("https://api.github.io"), from a python3 console run from the activated environment.

**Comment by jgbarah** [comment]
Hmmm. Another question: once you activated the virtualenv, and installed all requirements in it, did you install perceval in it as well?

**Comment by robinmuilwijk** [comment]
I will run that requests to api.github.com. And no, I did not re-install perceval. I had that installed already and figured I should not re-install this inside the virtualenv.

**Comment by jgbarah** [comment]
That would be certainly be a problem. You need to have everything in the virtualenv, and run perceval from there. But the perceval binary in your virtualenv. The other one is going to pull the systems libraries, which we already know have some trouble...

**Comment by robinmuilwijk** [comment]
ok, I will install perceval inside the virtualenv.

By the way, the requests.get on api.github.com will give me a 200

**Comment by jgbarah** [comment]
Good. That means that requests is working fine with api.github.io inside the virtualenv! Let's see what happens from perceval, but there should be no difference...

**Comment by robinmuilwijk** [comment]
I changed /usr/lib/python3.4/site-packages/perceval/backends/github.py and added the verify=False to line 291 again. and:

2016-06-12 20:14:53,518] - Sir Perceval completed his quest.

I can see data being parsed with usernames I recognize, so it works from what I can see. Now on to setting up the dashboard part. Thanks for all the help so far.

**Comment by robinmuilwijk** [comment]
Additional note; it actually runs outside the virtualenv, as long as I add verify=False to the  /usr/lib/python3.4/site-packages/perceval/backends/github.py

**Comment by jgbarah** [comment]
OK. Great it works! However, probably it is better that you make work it from within the virtualenv, because:

* You don't need to add verify=False, which means the certificate would be checked, which means a person-in-the-middle attack to get your GitHub credentials is less likely.
* You don't have to monkey-patch Perceval each time you upgrade it...

**Comment by sduenas** [comment]
@robinmuilwijk this is not related to your problem, but there's a bug in the GitHub and currently, user and password parameters are not used by this backend. The API token paremeter is available, though.

To create a token, follow the instructions on [GitHub](https://help.github.com/articles/creating-an-access-token-for-command-line-use/) and run Perceval as follows:

```
perceval github -t YOUR_TOKEN --owner elastic --repository filebeat --from-date '2016-01-01'
```
