### ISSUE TITLE
[Mediawiki] Using --from-date on recent mediawiki versions results in a exception (UTC Format related)

### ISSUE THREAD

**Issue by crisbal** [grimoirelab/perceval#54]
Hey there,

I want to report a bug:

Was testing perceval on our wiki project which uses mediawiki 1.27. 

Passing the --from-data params with a timestamp crashes the script.

For example:

```
[2016-09-01 18:26:41,164 - requests.packages.urllib3.connectionpool - DEBUG] - "GET /api.php?list=allrevisions&format=json&arvnamespace=0&action=query&arvstart=2015-06-01T00%3A00%3A00%2B00%3A00&arvprop=ids&arvlimit=max&arvdir=newer HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/home/crisbal/WikiToLearn/perceval/venv/lib/python3.5/site-packages/perceval/backends/mediawiki.py", line 494, in run
    for build in pages:
  File "/home/crisbal/WikiToLearn/perceval/venv/lib/python3.5/site-packages/perceval/backend.py", line 171, in decorator
    for data in func(self, *args, **kwargs):
  File "/home/crisbal/WikiToLearn/perceval/venv/lib/python3.5/site-packages/perceval/backends/mediawiki.py", line 110, in fetch
    for page_reviews in fetcher:
  File "/home/crisbal/WikiToLearn/perceval/venv/lib/python3.5/site-packages/perceval/backends/mediawiki.py", line 203, in __fetch_1_27
    pages_json = data_json['query']['allrevisions']
KeyError: 'query'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/crisbal/WikiToLearn/perceval/venv/bin/perceval", line 176, in <module>
    main()
  File "/home/crisbal/WikiToLearn/perceval/venv/bin/perceval", line 97, in main
    cmd.run()
  File "/home/crisbal/WikiToLearn/perceval/venv/lib/python3.5/site-packages/perceval/backends/mediawiki.py", line 505, in run
    raise RuntimeError(str(e))
RuntimeError: 'query'
```

The problem is that newer mediawiki versions refuse to work with the formatted timestamp produced by python (https://phabricator.wikimedia.org/T144482)

It's an issue that mediawiki devs have to fix but we could hack comething to make it work.

**Comment by acs** [comment]
Hi @crisbal!

Could you paste the perceval command line you executed to get that error?

Thanks!

**Comment by crisbal** [comment]
Ops, I forgot it! Sorry! 

`perceval -g mediawiki  'http://meta.wikitolearn.org' --from-date '2015-06-01'`

**Comment by albertinisg** [comment]
Hi @crisbal ! I've added a PR with a quick fix #55 . Checking it's phabricator ticket doesn't seems that it will be fixed in a short term of time, so better use one of the supported ones :smile: 

Thanks for the report!

**Comment by acs** [comment]
Ok, I see the problem. We must follow the format:

http://meta.wikitolearn.org/api.php?action=help&modules=main#main.2Fdatatypes

for the timestamp. Taking a look to the bug in MediaWiki you found, good catch

https://phabricator.wikimedia.org/T144482

it has received "Lowest priority" so we must fix it in our code. The fix is to not use timezone at all, ignore it and remove it, when we query MediaWiki API.

https://github.com/grimoirelab/perceval/pull/56

PR created to be reviewed by @sduenas.

Thanks @crisbal

**Comment by acs** [comment]
I am sorry @albertinisg ... when I answered and created the PR for this issues I have not seen you response and PR, which are also valid. So I would apply your #55 PR. Thanks!

**Comment by sduenas** [comment]
Fixed. Please update your repository to the latest version of master.

**Comment by crisbal** [comment]
Thank you guys! Amazing work! 

Keep up the good work, Perceval rocks!
