### ISSUE TITLE
phabricator backend broken for new phabricator versions

### ISSUE THREAD

**Issue by acs** [grimoirelab/perceval#80]
After upgrading our phabricator site when I try to use the perceval backend:

```
(acs@dellx) ~ $ perceval -g phabricator -t api-6b3df6XXXXXXXXXXXXX https://phabricator.bitergia.net
....
[2016-10-19 18:41:12,465 - root - INFO] - Sir Perceval is on his quest.
[2016-10-19 18:41:12,467 - perceval.backends.phabricator - INFO] - Fetching tasks of 'https://phabricator.bitergia.net' from 1970-01-01 00:00:00+00:00
[2016-10-19 18:41:12,467 - perceval.backends.phabricator - DEBUG] - Phabricator Conduit client requests: maniphest.search params: {'params': '{"constraints": [{"modifiedStart": 0}], "order": "outdated", "__conduit__": {"token": "api-6b3df67XXXXXXXXXX"}, "attachments": {"projects": true}}', '__conduit__': True, 'output': 'json'}
[2016-10-19 18:41:12,473 - requests.packages.urllib3.connectionpool - INFO] - Starting new HTTPS connection (1): phabricator.bitergia.net
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:794: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
[2016-10-19 18:41:12,726 - requests.packages.urllib3.connectionpool - DEBUG] - "POST /api/maniphest.search HTTP/1.1" 200 121
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.4.0.dev1-py3.5.egg/perceval/backends/phabricator.py", line 470, in run
    for task in tasks:
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.4.0.dev1-py3.5.egg/perceval/backend.py", line 181, in decorator
    for data in func(self, *args, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.4.0.dev1-py3.5.egg/perceval/backends/phabricator.py", line 82, in fetch
    for task in self.__fetch_tasks(from_date):
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.4.0.dev1-py3.5.egg/perceval/backends/phabricator.py", line 123, in __fetch_tasks
    for raw_tasks in self.client.tasks(from_date=from_date):
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.4.0.dev1-py3.5.egg/perceval/backends/phabricator.py", line 560, in tasks
    r = self._call(self.MANIPHEST_TASKS, params)
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.4.0.dev1-py3.5.egg/perceval/backends/phabricator.py", line 638, in _call
    code=result['error_code'])
perceval.backends.phabricator.ConduitError: Constraint "0" is not a valid constraint for this query. (code: ERR-CONDUIT-CORE)

```

**Comment by sduenas** [comment]
I reproduced the same error. It is a problem related with the way that parameters are given to the `Conduict` client. `constraints` parameter does not accept a list any longer, it accepts now a dictionary.
