### ISSUE TITLE
Parsing error with Askbot backend

### ISSUE THREAD

**Issue by acs** [grimoirelab/perceval#95]
```
(acs@dellx) (askbot *$%) ~/devel/GrimoireELK/utils $ ./p2o.py -g --index askbot-dev askbot 'http://askbot.org/' --from-date '2016-01-01'
...
2016-11-28 00:20:24,592 Fetching questions from 'http://askbot.org/': page 77/81
2016-11-28 00:20:25,974 Fetching HTML question 12583
2016-11-28 00:20:27,405 Fetching HTML question 10350
2016-11-28 00:20:28,833 Fetching HTML question 14382
2016-11-28 00:20:30,920 Fetching HTML question 7893
2016-11-28 00:20:31,048 Error feeding ocean from askbot (http://askbot.org/): 'data-comment-id'
Traceback (most recent call last):
  File "/home/acs/devel/GrimoireELK/utils/grimoire/arthur.py", line 98, in feed_backend
    ocean_backend.feed(backend_cmd.from_date)
  File "/home/acs/devel/GrimoireELK/utils/grimoire/ocean/elastic.py", line 186, in feed
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev1-py3.5.egg/perceval/backend.py", line 192, in decorator
    for data in func(self, *args, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev1-py3.5.egg/perceval/backends/core/askbot.py", line 90, in fetch
    question_obj = self.__build_question(html_question)
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev1-py3.5.egg/perceval/backends/core/askbot.py", line 188, in __build_question
    if AskbotParser.parse_question_comments(html_question[0]):
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev1-py3.5.egg/perceval/backends/core/askbot.py", line 315, in parse_question_comments
    question_comments = AskbotParser.parse_comments(comments)
  File "/usr/local/lib/python3.5/dist-packages/perceval-0.5.0.dev1-py3.5.egg/perceval/backends/core/askbot.py", line 433, in parse_comments
    'id': comment.attrs["data-comment-id"],
KeyError: 'data-comment-id'
```

**Comment by sduenas** [comment]
Fixed. Newer versions of askbok do not include that attribute within comments information.
